### ISSUE TITLE
[BUG] mongoose-lean-defaults doesn't seem to work globally

### ISSUE THREAD

**Issue by BaliTov** [DouglasGabr/mongoose-lean-defaults#11]
**Describe the bug**
When registering the plugin globally (https://mongoosejs.com/docs/plugins.html#global), it doesn't seem to work, while locally, it does.
 
**To Reproduce**
I tried this (pseudo)code:
```
const chai = require('chai');
const mongoose = require('mongoose');
mongoose.plugin(require('mongoose-lean-defaults'));

const { expect } = chai;

const uri = 'some-connection-uri';

const ExapmleSchema = {
 name: String,
 value: String,
 details: { type: String, default: 'Details' },
}

const MySchema = new.mongoose.Schema(ExapmleSchema, {collection: 'my-mongo-collection'});

describe ('Mongoose test', () => {
 it('should get defaults with lean', async () => {
   const connection = await mongoose.createConnection(uri);
   const myModel = await connection.model('model-name', MySchema);
   
   const leanWithDefault = await myModel
   .findOne({ id: ObjectId('5e1ad50070807bxxxxxxxxxx') })
   .lean({ defaults: true });
   
   const leanNoDefault = await myModel
   .findOne({ id: ObjectId('5d121836b996efxxxxxxxxxx') })
   .lean({ defaults: true });

   expect(leanWithDefault).to.have.property('details');
   expect(leanNoDefault).to.have.property('details');
 });
});
```

**Expected behavior**
the test should have passed, the plugin should have worked as is does locally.

**Actual behavior**
I received this error:
```
TypeError: this.projection is not a function
    at model.Query.attachDefaults (node_modules/mongoose-lean-defaults/index.js:52:29)
    at model.Query.<anonymous> (node_modules/mongoose-lean-defaults/index.js:33:20)
    at next (node_modules/kareem/index.js:186:14)
    at Kareem.execPost (node_modules/kareem/index.js:197:3)
    at node_modules/kareem/index.js:269:15
    at Immediate.cb (node_modules/mongoose/lib/query.js:1123:13)
    at Immediate.<anonymous> (node_modules/mquery/lib/utils.js:137:16)
```

**Additional context**
Mongoose version: `5.x`
Node version: `10.19.0`

**Comment by DouglasGabr** [comment]
@BaliTov thank you for opening the issue.

I've tested with mongoose version 5.7.5, and it worked fine, no errors. Can you provide the exact mongoose version you're using?

**Comment by BaliTov** [comment]
@DouglasGabr , I'm using version 5.x

**Comment by DouglasGabr** [comment]
@BaliTov great! I'm using the mongoose version ^5.6.4 in the devDependencies, I'm probably using some feature that was added after 5.0.x. Thanks for pointing this kind of problem, I'll make sure to add a peerDependencies in the package.json, so when the package it's installed, npm will warn if the mongoose version is outdated.

I'll close this issue, feel free to open a new one if you face any other bug or have some feature suggestion :rocket:
