### ISSUE TITLE
First param to `schema.plugin()` must be a function, got "object"

### ISSUE THREAD

**Issue by saudraisn** [DouglasGabr/mongoose-lean-defaults#19]
**Describe the bug**
Going from v1.0.1 to v1.1.0 is in fact a breaking change. Since we have a project that imports

"mongoose-lean-defaults": "^1.0.1" (notice that we allow minor version upgrades with "^"), 
the minor version was bumped to v1.1.1 when doing an upgrade, causing this issue :

![image](https://user-images.githubusercontent.com/6865470/118045040-698e9780-b345-11eb-83ac-7a1333998b64.png)
 
Perhaps changing this package's version to 2.0.0 for that breaking change (v1.1.0) (following the [semver](https://semver.org/) system) would be a good idea to save other people some troubleshooting time.

All in all, thanks a lot for that great plugin.

**Additional context**  
Mongoose version:  5.10.6
Node version: 14.15.1

**Comment by DouglasGabr** [comment]
@saudraisn I think you're right, I've noticed that using typescript it exports a `default` property only after I had published the version, it is better to deprecate 1.1.1 and re-publish it as 2.0.0. I'll do that right now
