### ISSUE TITLE
Update mongoose peer dependancy

### ISSUE THREAD

**Issue by Poyoman39** [DouglasGabr/mongoose-lean-defaults#22]
Mongoose just has v6 gone out and peer dependency has v5 as peer dependency.

Would it be possible to make it v6 ?

```
  "peerDependencies": {
    "mongoose": "^5.6.4"
  },
```

**Comment by DouglasGabr** [comment]
@Poyoman39 sorry for the late reply. I see you opened a pull request, thanks for that, I'll not use it tho because I'm working on closing all of the issues so I'll update the mongoose version on `peerDependencies` myself.
