### ISSUE TITLE
[FEATURE] Turn defaults globally on

### ISSUE THREAD

**Issue by kasium** [DouglasGabr/mongoose-lean-defaults#28]
**Is your feature request related to a problem? Please describe.**  
For each call of `lean` I need to pass `{defaults: true}` which is a bit redundant and in bigger projects, it's easy to forget one.

**Describe the solution you'd like**  
A way to turn default globally on, meaning that every `lean()` call tries to resolve defaults, even if no `{defaults: true}` is passed.

**Comment by DouglasGabr** [comment]
Thanks for the feature request. I'll work on it, I'll probably make it available as a second argument in `.plugin()`
