### ISSUE TITLE
[FEATURE] lean defaults with projection

### ISSUE THREAD

**Issue by corsa1r** [DouglasGabr/mongoose-lean-defaults#7]
It would be convenient to have the option to make the lean result to match the projection structure in the query.

```js
// Example Mongoose.Schema
{
  id: Number,
  first_name: { type: String, default: 'Foo'},
  last_name: { type: String, default: 'Bar' }
}

//Example Query
User
    .findOne({ id }, { first_name: 1 })
    .lean({ defaults: true })

// This will return the last_name as well
// It would be awesome to follow the projection required in the query

**Comment by DouglasGabr** [comment]
Thanks for the suggestion @corsa1r. I definitely will work on that

**Comment by DouglasGabr** [comment]
added in [v0.4.0](https://github.com/DouglasGabr/mongoose-lean-defaults/releases/tag/v0.4.0) (https://github.com/DouglasGabr/mongoose-lean-defaults/commit/f0affd4df8df4a163659731c8cec703448c578f8)
