### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Poyoman39** [DouglasGabr/mongoose-lean-defaults#9]
**Describe the bug**
When using `.lean({ defaults: true })` in a query with projection, and considering a field is undefined, the default is not set by lean, even if the projection includes fields with default values.

**To Reproduce**

Here is a shema sample :
```
const firmSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    unique: true,
  },

  features: {
    someFeature: {
      type: Boolean,
      default: false,
    },
  },
});
```

And here is a problematic request:
`models.Firm.findOne({ name: 'Evotec' }, 'name features').lean({ defaults: true }).exec()`

**Expected behavior**
The features field should be filled with defaults

**Comment by Poyoman39** [comment]
It's highly probable the issue come from the fact the "default" attribute is not on root of the schema attribute

**Comment by corsa1r** [comment]
Hey @Poyoman39 can you review the issue, so i believe i fixed this exact problem with my PR. #8

**Comment by Poyoman39** [comment]
I confirm this is working for me ! :) Thank you for your time :)

**Comment by Poyoman39** [comment]
Should i close the issue ?
